version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.0
    commands:
      - cd ..
      - yum install -y which
      - yum install -y nuget
      - yum install -y which
      - pip install --no-cache-dir lit OutputCheck pyyaml
      - mozroots --import --sync
      # Get Boogie
      - git clone https://github.com/boogie-org/boogie.git
      - nuget restore boogie/Source/Boogie.sln
      - msbuild boogie/Source/Boogie.sln
      # Get Dafny
      - git clone https://github.com/microsoft/dafny.git
      - msbuild dafny/Source/Dafny.sln
      - export PATH="$PWD/dafny/Binaries:$PATH"
      # Get Z3
      - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-14.04.zip
      - unzip z3*.zip && rm *.zip
      - cp -r z3* dafny/Binaries/z3
      - cd aws-encryption-sdk-dafny
      # Check AWS config
      - aws kms generate-data-key --key-id "arn:aws:kms:us-west-2:658956600833:key/b3537ef1-d8dc-4780-9f5a-55776cbb2f7f" --region "us-west-2" --key-spec AES_256
  build:
    commands:
      - make release
