version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: dafny_verify
      buildspec: codebuild/dafny/verify.yml
    - identifier: dotnet_tests
      buildspec: codebuild/dotnet/tests.yml
    - identifier: dotnet_vectors
      buildspec: codebuild/dotnet/test-vectors.yml
    - identifier: dotnet_generate_vectors
      buildspec: codebuild/dotnet/generate-test-vectors.yml
    - identifier: dotnet_release_staging 
      buildspec: codebuild/dotnet/release-staging.yml
    - identifier: dotnet_examples_net5_0
      buildspec: codebuild/dotnet/examples.yml
      env:
        variables:
          DOTNET_TARGET_VERSION: net5.0
    - identifier: dotnet_examples_net3_1
      buildspec: codebuild/dotnet/examples.yml
      env:
        variables:
          DOTNET_TARGET_VERSION: netcoreapp3.1
    - identifier: dotnet_examples_net_shouldnt_work
      buildspec: codebuild/dotnet/examples.yml
      env:
        variables:
          DOTNET_TARGET_VERSION: net47
    - identifier: dotnet_examples_windows
      buildspec: codebuild/dotnet/examples.yml
      env:
        image: aws/codebuild/windows-base:2019-1.0
        variables:
          DOTNET_TARGET_VERSION: net5.0
