version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.0
    commands:
      - cd ..
      - yum install -y which
      - yum install -y nuget
      - mozroots --import --sync
      # Get Boogie
      # Multiple Boogie commits have broken our build or test cases. Locking down Boogie.
      - git clone --branch v2.4.2 https://github.com/boogie-org/boogie.git
      - nuget restore boogie/Source/Boogie.sln
      - msbuild boogie/Source/Boogie.sln
      # Get Dafny
      - git clone https://github.com/microsoft/dafny.git
      # Although Dafny does have releases, we often need a newer hash than the latest release, while still needing the
      # the security of reproducible builds.
      - cd dafny
      - git reset --hard 3f31d66499ab5e2e5d9a7b21f541de5b1d3eb585
      - cd ..
      - nuget restore dafny/Source/Dafny.sln
      - msbuild dafny/Source/Dafny.sln
      - export PATH="$PWD/dafny/Binaries:$PATH"
      # Get Z3
      - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-14.04.zip
      - unzip z3*.zip && rm *.zip
      - cp -r z3* dafny/Binaries/z3
      - cd aws-encryption-sdk-dafny
      # Set up environment for running test vectors
      - wget https://github.com/awslabs/aws-encryption-sdk-test-vectors/raw/master/vectors/awses-decrypt/python-1.3.8.zip
      - unzip python-1.3.8.zip && rm python-1.3.8.zip
      - export DAFNY_AWS_ESDK_TEST_VECTOR_MANIFEST_PATH="${PWD}/manifest.json"
      - export DAFNY_AWS_ESDK_DECRYPT_ORACLE_URL="http://xi1mwx3ttb.execute-api.us-west-2.amazonaws.com/api/v0/decrypt"
  build:
    commands:
      - dotnet build -t:VerifyDafny src
      - dotnet build -t:VerifyDafny test
      - dotnet test
      - dotnet test testVectors
