version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
    commands:
      - cd ..
      # - yum install -y which
      # - yum install -y nuget
      # - mozroots --import --sync
      # Get Boogie
      - git clone --branch v2.4.21 https://github.com/boogie-org/boogie.git
      - dotnet restore boogie/Source/Boogie.sln
      - dotnet build boogie/Source/Boogie.sln
      # Get Dafny
      - git clone https://github.com/microsoft/dafny.git
      # Although Dafny does have releases, we often need a newer hash than the latest release, while still needing the
      # the security of reproducible builds.
      - cd dafny
      - git reset --hard df707bc07e3c39390286dfd0c1576d0a3f556f8b
      - cd ..
      - dotnet restore dafny/Source/Dafny.sln
      - dotnet dafny/Source/Dafny.sln
      - export PATH="$PWD/dafny/Binaries:$PATH"
      # Get Z3
      - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-14.04.zip
      - unzip z3*.zip && rm *.zip
      - cp -r z3* dafny/Binaries/z3
      - cd aws-encryption-sdk-dafny
  build:
    commands:
      # Currently, test depends on src, so verifying test will also verify src
      # TODO-RS: Move the parallel verification task into the dafny CLI itself
      - dotnet build -t:VerifyDafny test
