version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: dafny_verify
      buildspec: codebuild/dafny/verify.yml
    - identifier: duvet
      buildspec: codebuild/dafny/duvet.yml
    - identifier: dotnet 
      buildspec: codebuild/dotnet/ci.yml
