version: 0.2
env:
  variables:
    VECTOR_URL: "https://github.com/awslabs/aws-encryption-sdk-test-vectors/raw/a28851a188163e45b8cbf94c1d5a1e67e9622aa8/vectors/awses-decrypt/python-1.3.8.zip"
    ORACLE_URL: "http://xi1mwx3ttb.execute-api.us-west-2.amazonaws.com/api/v0/decrypt"
phases:
  install:
    runtime-versions:
      dotnet: 3.0
    commands:
      - cd ..
      - yum install -y which
      - yum install -y nuget
      - yum install -y unzip
      - pip install --no-cache-dir lit OutputCheck pyyaml
      - mozroots --import --sync
      # Get Boogie
      - git clone https://github.com/boogie-org/boogie.git
      - nuget restore boogie/Source/Boogie.sln
      - msbuild boogie/Source/Boogie.sln
      # Get Dafny
      - git clone https://github.com/microsoft/dafny.git
      - msbuild dafny/Source/Dafny.sln
      - export PATH="$PWD/dafny/Binaries:$PATH"
      # Get Z3
      - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-14.04.zip
      - unzip z3*.zip && rm *.zip
      - cp -r z3* dafny/Binaries/z3
      - cd aws-encryption-sdk-dafny
      # Get test vectors
      - wget $VECTOR_URL
  build:
    commands:
      - dotnet build -t:VerifyDafny src
      - dotnet build -t:VerifyDafny test
      - dotnet test
      - cd testVectors
      - unzip ../python-1.3.8.zip
      - dotnet run decrypt --vectorDir .
      - dotnet run encrypt --vectorDir . -o $ORACLE_URL
