version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 2.2
    commands:
      - cd ..
      - yum install -y nuget
      - pip install --no-cache-dir lit OutputCheck pyyaml
      - mozroots --import --sync
      # Get Boogie
      - git clone https://github.com/boogie-org/boogie.git
      - nuget restore boogie/Source/Boogie.sln
      - xbuild boogie/Source/Boogie.sln
      # Get Dafny
      - git clone https://github.com/microsoft/dafny.git
      - msbuild dafny/Source/Dafny.sln
      - export PATH="$PWD/dafny/Binaries:$PATH"
      # Get Z3
      - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-14.04.zip
      - unzip z3*.zip && rm *.zip
      - cp -r z3* dafny/Binaries/z3
      - cd aws-encryption-sdk-dafny
  build:
    commands:
      - make release
