version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
    commands:
      - cd ..
      # Get Dafny
      - curl https://github.com/dafny-lang/dafny/releases/download/v3.1.0/dafny-3.1.0-x64-osx-10.14.2.zip -L -o dafny.zip
      - unzip dafny.zip && rm dafny.zip
      - export PATH="$PWD/dafny/Binaries:$PATH"
      - cd aws-encryption-sdk-dafny
  build:
    commands:
      # Currently, test depends on src, so verifying test will also verify src
      # TODO-RS: Move the parallel verification task into the dafny CLI itself
      - dotnet build -t:VerifyDafny -p:VerifyDafnyJobs=1 test
