version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: dafny_verify
      buildspec: codebuild/dafny/verify.yml
      # The GitHub Actions verification job on Mac OS is the definitive build task,
      # and Dafny does not behave consistently across platforms, so this one
      # sometimes fails spuriously.
      # See https://github.com/dafny-lang/dafny/issues/1807
      # It is useful to gather data on when these inconsistencies occur,
      # so we still run this task but ignore failures.
      ignore-failure: true
    - identifier: dotnet_tests
      buildspec: codebuild/dotnet/tests.yml
    - identifier: dotnet_vectors
      buildspec: codebuild/dotnet/test-vectors.yml
    - identifier: dotnet_generate_vectors
      buildspec: codebuild/dotnet/generate-test-vectors.yml
    - identifier: dotnet_tests_windows
      buildspec: codebuild/dotnet/tests-windows.yml
      env:
        type: WINDOWS_SERVER_2019_CONTAINER
        image: aws/codebuild/windows-base:2019-1.0
    - identifier: dotnet_benchmark_windows
      buildspec: codebuild/dotnet/benchmark-windows.yml
      env:
        type: WINDOWS_SERVER_2019_CONTAINER
        image: aws/codebuild/windows-base:2019-1.0
