version: 0.2
phases:
  install:
    commands:
      - cd ..
      # Get Dafny
      - curl https://github.com/dafny-lang/dafny/releases/download/v3.3.0/dafny-3.3.0-x64-ubuntu-16.04.zip -L -o dafny.zip
      - unzip dafny.zip && rm dafny.zip
      - export PATH="$PWD/dafny:$PATH"
      - cd aws-encryption-sdk-dafny
  build:
    commands:
      # Currently, test depends on src, so verifying test will also verify src
      # TODO-RS: Move the parallel verification task into the dafny CLI itself
      - dotnet build -t:VerifyDafny -p:TestVerifyOverride="verificationLogger:trx" test
reports:
    Dafny:
        file-format: VisualStudioTrx
        files:
            - '**/*'
        base-directory: 'test/TestResults'
