version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: dafny_verify
      buildspec: codebuild/dafny/verify.yml
    - identifier: dotnet_tests
      buildspec: codebuild/dotnet/tests.yml
    - identifier: dotnet_examples
      buildspec: codebuild/dotnet/examples.yml
    - identifier: dotnet_vectors
      buildspec: codebuild/dotnet/test-vectors.yml
    - identifier: dotnet_generate_vectors
      buildspec: codebuild/dotnet/generate-test-vectors.yml
    - identifier: dotnet_release_staging 
      buildspec: codebuild/dotnet/release-staging.yml
    - identifier: dotnet_tests_windows
      buildspec: codebuild/dotnet/tests-windows.yml
