AWSTemplateFormatVersion: "2010-09-09"
Description: "DDB Table and IAM Managed Policies/Role for AWS KMS Hierarchical Keyring Testing"

Parameters:
  TableName:
    Type: String
    Description: Test Table Name
    Default: HierarchicalKeyringTestTable
  KeyStoreTable:
    Type: String
    Description: Key Store Test Table Name
    Default: KeyStoreTestTable
  ProjectName:
    Type: String
    Description: A prefix that will be applied to any names
    Default: Public-ESDK-Dafny
  GitHubRepo:
    Type: String
    Description: GitHub Repo that invokes CI
    Default: aws/aws-encryption-sdk-dafny

Resources:
  GitHubCIRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub "GitHub-CI-${ProjectName}-Role-${AWS::Region}"
      Description: "Access DDB, KMS, Resources for CI from GitHub"
      ManagedPolicyArns:
        - "arn:aws:iam::370957321024:policy/ESDK-Dafny-DDB-ReadWriteDelete-us-west-2"
        - "arn:aws:iam::370957321024:policy/Hierarchical-GitHub-KMS-Key-Policy"
        - "arn:aws:iam::370957321024:policy/KMS-Public-CMK-EncryptDecrypt-Key-Access"
        - "arn:aws:iam::370957321024:policy/RSA-GitHub-KMS-Key-Policy"
      AssumeRolePolicyDocument: !Sub |
        {
          "Version": "2012-10-17",   
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": { "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com" },
              "Action": "sts:AssumeRoleWithWebIdentity",
              "Condition": {
                "StringEquals": {
                  "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
                },
                "StringLike": {
                  "token.actions.githubusercontent.com:sub": "repo:${GitHubRepo}:*"
                }
              }
            },
            {
              "Effect": "Allow",
              "Principal": { "AWS": "arn:aws:iam::${AWS::AccountId}:role/ToolsDevelopment" },
              "Action": "sts:AssumeRole"
            }
          ]
        }
