# This workflow performs static analysis checks.
name: ComAmazonawsKms

on: 
  pull_request:
  push:
    branches:
      - mainline

jobs:
  verification:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    steps:
      - uses: actions/checkout@v2
      # The specification submodule is private so we don't have access, but we don't need
      # it to verify the Dafny code. Instead we manually pull the submodule we DO need.
      - run: git submodule update --init libraries

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1.4.0
        with:
          dafny-version: "3.9.0"

      - name: Verify Dafny code
        shell: bash
        working-directory: ./ComAmazonawsKms
        run: |
          # This works because `node` is installed by default on GHA runners
          CORES=$(node -e 'console.log(os.cpus().length)')
          make verify CORES=$CORES

      - if: always()
        shell: bash
        run: MAX_VERIFICATION_DURATION_SECONDS=10 python3 verification-times-from-trx.py ComAmazonawsKms/TestResults/*.trx

  test:
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::405437749609:role/Github-OICD-for-private-aws-encryption-sdk-da-Role-15BEGAP519YZV
          role-session-name: NetTests

      - uses: actions/checkout@v3
      # The specification submodule is private so we don't have access, but we don't need
      # it to verify the Dafny code. Instead we manually pull the submodule we DO need.
      - run: git submodule update --init libraries

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1.4.0
        with:
          dafny-version: "3.9.0"

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Download Dependencies 
        working-directory: ./ComAmazonawsKms
        run: make setup_net

      - name: Compile implementation
        shell: bash
        working-directory: ./ComAmazonawsKms
        run: |
          # This works because `node` is installed by default on GHA runners
          CORES=$(node -e 'console.log(os.cpus().length)')
          make compile_net CORES=$CORES

      - name: Test
        working-directory: ./ComAmazonawsKms
        run: make test_net
