# This workflow runs every weekday at 15:00 UTC (8AM PDT)
name: Daily CI

on:
  schedule:
    - cron: "00 15 * * 1-5"

jobs:
  daily-ci-verification:
    # Don't run the cron builds on forks
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    uses: ./.github/workflows/library_dafny_verification.yml
    with:
      dafny: '4.2.0'
  daily-ci-java:
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    uses: ./.github/workflows/library_java_tests.yml
    with:
      dafny: '4.2.0'
  daily-ci-net:
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    uses: ./.github/workflows/library_net_tests.yml
    with:
      dafny: '4.2.0'
