# This workflow verifies
# that the source is annotated
# with respect to the specification
name: Duvet report

on: 
  pull_request:
  push:
    branches:
      - public-v4

jobs:
  duvet:
    runs-on: ubuntu-latest
    # This environment stores a token
    # that can be used to checkout
    # the ESDK specification
    environment: "Duvet CI"
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    steps:
      - name: Support longpaths on Git checkout
        run: |
          git config --global core.longpaths true
      
      - uses: actions/checkout@v3
        with:
         submodules: true

      - name: Install duvet
        shell: bash
        run: |
          cargo +stable install duvet

      # //= aws-encryption-sdk-specification/framework/structures.md#overview
      # //= type=implication
      # //# These structures define a group of related fields that MUST hold certain properties.
      # //# Wherever these structures are referenced in this specification,
      # //# implementations MUST ensure that all properties of a structure's fields are upheld.
      - name: Run the duvet report
        shell: bash
        run: |
          make duvet

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: specification_compliance_report
          path: specification_compliance_report.html
