# This workflow performs tests in .NET.
name: Library Java tests

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  testJava:
    strategy:
      matrix:
        library: [
          AwsCryptographyPrimitives,
          ComAmazonawsKms,
          ComAmazonawsDynamodb,
          AwsCryptographicMaterialProviders,
          StandardLibrary
        ]
        java-version: [ 8, 11, 16, 17 ]
        os: [
          # TODO just test on mac for now
          #windows-latest,
          #ubuntu-latest,
          macos-latest
        ]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          # TODO: This role was manually created.
          role-to-assume: arn:aws:iam::370957321024:role/ESDK-Dafny-Private-CA-Read
          role-session-name: JavaPrivateESDKDafnyTests

      - uses: actions/checkout@v3
      # The specification submodule is private so we don't have access, but we don't need
      # it to verify the Dafny code. Instead we manually pull the submodule we DO need.
      - run: git submodule update --init libraries

      # Set up env vars for CodeArtifact
      - name: Set Up Env Vars for CodeArtifact
        run: |
          export URL=`aws codeartifact get-repository-endpoint \
            --domain github-polymorph \
            --domain-owner "370957321024" \
            --repository DafnyJavaConversion \
            --format maven | jq -r .repositoryEndpoint`
          export TOKEN=`aws codeartifact get-authorization-token \
            --domain github-polymorph \
            --domain-owner "370957321024" \
            --query authorizationToken \
            --output text`
          echo "CODEARTIFACT_URL_JAVA_CONVERSION=$URL" >> $GITHUB_ENV
          echo "CODEARTIFACT_AUTH_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1.4.0
        with:
          dafny-version: "nightly-2022-12-02-edab6cc"

      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java-version }}

      # Java DafnyRuntime is not published to maven,
      # so manually download a nightly build for 3.10.0 and grab it from there.
      - name: Locally Cache Java DafnyRuntime
        run: |
          wget https://github.com/dafny-lang/dafny/releases/download/nightly/dafny-nightly-2022-12-02-edab6cc-x64-osx-10.14.2.zip 
          unzip dafny-nightly-2022-12-02-edab6cc-x64-osx-10.14.2.zip 
          mvn install:install-file \
          -Dfile=dafny/DafnyRuntime.jar \
          -DgroupId=dafny.lang \
          -DartifactId=DafnyRuntime \
          -Dversion=3.10.0 \
          -DgeneratePom=true \
          -Dpackaging=jar

      - name: Build ${{ matrix.library }} implementation
        shell: bash
        working-directory: ./${{ matrix.library }}
        run: |
          # This works because `node` is installed by default on GHA runners
          CORES=$(node -e 'console.log(os.cpus().length)')
          make build_java CORES=$CORES

      # KMS tests need to use credentials which can call KMS
      - name: Configure AWS Credentials for Tests
        uses: aws-actions/configure-aws-credentials@v1
        if: matrix.library == 'ComAmazonawsKms'
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::405437749609:role/Github-OICD-for-private-aws-encryption-sdk-da-Role-15BEGAP519YZV
          role-session-name: JavaTests

      - name: Test ${{ matrix.library }}
        working-directory: ./${{ matrix.library }}
        # TODO: only tests with implemented externs may be run currently
        if: matrix.library == 'StandardLibrary' || matrix.library == 'ComAmazonawsKms'
        run: |
          make test_java
