# This workflow runs for every pull request
name: PR CI

on:
  pull_request:

jobs:
  pr-ci-codegen:
    uses: ./.github/workflows/library_codegen.yml
    with:
      dafny: '4.8.1'
  pr-ci-verification:
    uses: ./.github/workflows/library_dafny_verification.yml
    with:
      dafny: '4.8.1'
  # pr-ci-java:
  #   uses: ./.github/workflows/library_java_tests.yml
  #   with:
  #     dafny: '4.2.0'
  pr-ci-net:
    uses: ./.github/workflows/library_net_tests.yml
    with:
      dafny: '4.8.1'
  pr-ci-rust:
    uses: ./.github/workflows/library_rust_tests.yml
    with:
      dafny: '4.8.1'
  pr-test-vectors:
    uses: ./.github/workflows/library_interop_tests.yml
    with:
      dafny: '4.8.1'
