# This workflow runs for every push to main
name: Push CI

on:
  push:
    branches:
      - main    

jobs:
  pr-ci-codegen:
    uses: ./.github/workflows/library_codegen.yml
    with:
      dafny: '4.2.0'
  push-ci-verification:
    uses: ./.github/workflows/library_dafny_verification.yml
    with:
      dafny: '4.7.0'
  # push-ci-java:
  #   uses: ./.github/workflows/library_java_tests.yml
  #   with:
  #     dafny: '4.2.0'
  push-ci-net:
    uses: ./.github/workflows/library_net_tests.yml
    with:
      dafny: '4.2.0'
  pr-test-vectors:
    uses: ./.github/workflows/library_interop_tests.yml
    with:
      dafny: '4.2.0'
