# This workflow runs for every push to main
name: Push CI

on:
  push:
    branches:
      - main    

jobs:
  push-ci-format:
    uses: ./.github/workflows/library_dafny_format.yml
    with:
      dafny: '4.2.0'
  push-ci-verification:
    uses: ./.github/workflows/library_dafny_verification.yml
    with:
      dafny: '4.2.0'
  push-ci-java:
    uses: ./.github/workflows/library_java_tests.yml
    with:
      dafny: '4.2.0'
  push-ci-net:
    uses: ./.github/workflows/library_net_tests.yml
    with:
      dafny: '4.2.0'
