# This workflow performs static analysis checks.
name: verification

on: ["pull_request", "push"]

jobs:
  verification:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      # Remove the existing dotnet alias, as suggested by homebrew
      - name: Remove existing dotnet on GHA runner
        run: rm /usr/local/bin/dotnet
      
      - name: Setup Dafny
        run: |
          brew update
          brew install dafny@3.1.0

      - name: Verify Dafny code
        # Currently, test depends on src, so verifying test will also verify src
        # TODO-RS: Move the parallel verification task into the dafny CLI itself
        run: dotnet build -t:VerifyDafny -p:VerifyDafnyJobs=1 test
