# This workflow performs static analysis checks.
name: verification

on: ["pull_request", "push"]

jobs:
  verification:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1
        with:
          dafny-version: "3.3.0"

      - name: Verify Dafny code
        # Currently, test depends on src, so verifying test will also verify src
        run: dotnet build -t:VerifyDafny -p:VerifyDafnyJobs=2 -p:TestVerifyOverride="verificationLogger:trx" test
